name: Generate WARP config (wgcf)

on:
  workflow_dispatch: {}

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install jq
        run: |
          sudo apt-get update
          sudo apt-get install -y jq

      - name: Download wgcf
        run: |
          RAW_VER=$(curl -fsSL https://api.github.com/repos/ViRb3/wgcf/releases/latest | jq -r '.tag_name')
          WGCF_VERSION="${RAW_VER#v}"
          echo "Latest wgcf version: $WGCF_VERSION"
          curl -fsSL -o wgcf.tar.gz \
            https://github.com/ViRb3/wgcf/releases/download/v${WGCF_VERSION}/wgcf_${WGCF_VERSION}_linux_amd64.tar.gz
          tar xzf wgcf.tar.gz
          chmod +x wgcf
          ls -l

      - name: Register WARP account
        run: |
          yes | ./wgcf register
          ls -l

      - name: Generate WireGuard profile
        run: |
          ./wgcf generate
          ls -l

      - name: Upload config
        uses: actions/upload-artifact@v4
        with:
          name: wgcf-profile
          path: wgcf-profile.conf
